name: Build PHP
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'PHP version to build'
        required: true
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
        arch: [arm64]
        ts: [nts, ts]
    runs-on: windows-2022
    steps:
      - name: Checkout php-ftw
        uses: actions/checkout@v4
      - name: Checkout php-sdk
        uses: actions/checkout@v4
        with:
          repository: 'php/php-sdk-binary-tools'
          ref: 'php-sdk-2.3.0'
          path: 'php-sdk'
#      - name: Install OCI
#        run: powershell .github/workflows/install-oci.ps1 -arch ${{matrix.arch}}
      - name: Fetch php-src
        run: powershell .github/workflows/fetch-php-src.ps1 -version ${{github.event.inputs.version}} -arch ${{matrix.arch}} -ts ${{matrix.ts}}
      - name: Build php
        run: powershell .github/workflows/build.ps1 -version ${{github.event.inputs.version}} -arch ${{matrix.arch}} -ts ${{matrix.ts}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{matrix.ts}}-${{matrix.arch}}
          path: artifacts-${{matrix.ts}}-${{matrix.arch}}
