name: Test PHP
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'PHP version to test'
        required: true
defaults:
  run:
    shell: cmd
jobs:
  test:
    strategy:
      matrix:
        arch: [x64, x86]
        ts: [nts, ts]
        opcache: [nocache, opcache]
    runs-on: windows-2019
    steps:
      - name: Checkout php-ftw
        uses: actions/checkout@v2
      - name: Setup MySQL
        uses: ankane/setup-mysql@v1
        with:
          database: test
      - name: Fetch PHP
        run: powershell .github/workflows/fetch-php.ps1 -version 8.0.7RC1 -arch ${{matrix.arch}} -ts ${{matrix.ts}}
      - name: Run tests
        run: powershell .github/workflows/run-tests.ps1 -arch ${{matrix.arch}} -opcache ${{matrix.opcache}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results.xml
          path: tests-results.xml
